### ISSUE TITLE
Feature #1: User can start app and user location will center on map

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/tesla-supercharger#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start app and user location pin will be dropped on map.

## 📐 Functionality

> ##### User can start app and user location pin will be dropped on map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/163869945-46b04d5b-c577-4331-9e29-63ce6aa1aa46.png)
![image](https://user-images.githubusercontent.com/96906988/163869996-a20bc3cc-d2b3-4205-b8e7-119550995755.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML, CSS, JS files. Create HTML skeleton.
- [x] Incorporate API to center map to user location on app load.
- [x] Display user's current location.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
333
