### ISSUE TITLE
Feature #2: User can view nearest Tesla Supercharger on app load.

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/tesla-supercharger#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view nearest Tesla Supercharger on app load.

## 📐 Functionality

> ##### User can view nearest Tesla Supercharger on app load.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/163871396-3c876b5c-6d78-4137-b295-1d6ea47fc97a.png)
![image](https://user-images.githubusercontent.com/96906988/163871421-52559afe-213d-4963-81ce-cb1a31a6df8c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] On app load, automatically drop pin for nearest Tesla Supercharger based on user location.
- [x] Said charging station info will be provided, such as address.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
