### ISSUE TITLE
Feature #3: User can view navigation route.

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/tesla-supercharger#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view navigation route.

## 📐 Functionality

> ##### User can view navigation route.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/163871557-13225ea4-3c90-452d-896f-637bf70eb00f.png)
![image](https://user-images.githubusercontent.com/96906988/163871611-c8394df7-19f4-4604-bc1d-b0b6197d2c27.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Implement API to display navigation route (in blue) between user location and nearest Tesla supercharger.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by theDanielYeh** [comment]
Issue #2 feature's API response satisfies Issue #3 functionality. No mod to code.
