### ISSUE TITLE
Feature #4: User can view weather condition at nearest Tesla Supercharger station.

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/tesla-supercharger#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view weather condition at nearest Tesla Supercharger station.

## 📐 Functionality

> ##### User can view weather condition at nearest Tesla Supercharger station.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/163871854-85cd8d89-7664-4758-be36-22f19444ecf0.png)
![image](https://user-images.githubusercontent.com/96906988/163871874-2197fbac-e4e5-475a-9a4c-feb338ecf498.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Home page will display weather condition at the nearest Tesla Supercharger.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
