### ISSUE TITLE
Feature #5: User can save favorite stations.

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/tesla-supercharger#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save favorite stations.

## 📐 Functionality

> ##### User can save favorite stations.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/163872246-b9f7ea81-f63a-422a-93e4-c5449dc51371.png)
![image](https://user-images.githubusercontent.com/96906988/163872275-c47cf332-fdc3-4cce-9020-d48f1ed29b72.png)
![image](https://user-images.githubusercontent.com/96906988/163872313-b498c014-0a99-46a7-b082-72884b6135c6.png)
![image](https://user-images.githubusercontent.com/96906988/163872337-8a25e0e8-2876-40b1-aa78-493acd643de6.png)
![image](https://user-images.githubusercontent.com/96906988/163872377-f0a0e7b9-a5a5-4b17-b300-0a66451f17c3.png)
![image](https://user-images.githubusercontent.com/96906988/163872532-74c27b51-11d5-4546-8c29-12296bf75dcb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can click a lightning bolt icon to toggle save. The icon will reflect that is saved.
- [x] User can click on "My Favorites" to view list of saved stations.
- [x] User can click on lightning bolt icon to remove from "My Favorites" list.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
